name: Deploy App

on:
  release:
    types: [published]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: remote ssh
      #   uses: appleboy/ssh-action@4330a1ea489ced98a6778fb35bb6bfed8b61fca5
      #   with:
      #     host: ${{secrets.HOST}}
      #     username: ${{secrets.USER}}
      #     password: ${{secrets.PW}}
      #     timeout: 120s
      #     script: |
      #       pwd
      #       echo ${{secrets.HOST}} | base64
      - run: git fetch origin main
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.x
      - name: npm install
        run: npm ci
      - name: stamp version number
        if: github.event_name == 'release'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "vX.X.X"
          replace: "v${{ github.event.release.tag_name }}"
          regex: false
          include: "src/shared/chunks/footer/**"
      - name: build
        run: npm run build
      - name: Zip Dist
        working-directory: ./dist/portfolio3/browser/
        run: tar -cvf portfolio-release-web.tar ./
      - name: copy scp
        uses: appleboy/scp-action@3710327b67602586de2a7681d53fb1c009105c5d
        with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USER}}
            password: ${{secrets.PW}}
            source: ./dist/portfolio3/browser/portfolio-release-web.tar
            target: ~/webapps/auto-deploy/portfolio3/
            strip_components: 3
            timeout: 120s
      - name: remote ssh
        uses: appleboy/ssh-action@4330a1ea489ced98a6778fb35bb6bfed8b61fca5
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          password: ${{secrets.PW}}
          script: |
            whoami
            cd webapps/auto-deploy/portfolio3/
            rm -r /var/www/fernsten.me/portfolio3/*
            tar -xvf portfolio-release-web.tar --directory /var/www/fernsten.me/portfolio3

